swagger: '2.0'
info:
  title: Apache Sling Resource API
  description: 'API for interacting with a Sling system.'
  contact:
    name: Bryan Stopp
    email: bryan.stopp@gmail.com
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '1.0.0'

host: localhost:8080
basePath: /

schemes:
  - http
  - https

paths:
  /{resource}.json:
    get:
      summary: Get a resource
      description: Returns a representation of a Sling resource.
      operationId: resource
      produces:
        - application/json
      parameters:
        - name: resource
          in: path
          description: The relative path to the resource.
          required: true
          type: string
      responses:
        '200':
          description: Successful
          schema:
            type: object
            additionalProperties:
              type: string
        '404':
          $ref: '#/responses/NotFound'
        '500':
          $ref: '#/responses/ServerError'

#definitions:


responses:
  Unauthorized:
    description: Unauthorized
  Forbidden:
    description: Forbidden (ACL)
  NotFound:
    description: Not Found
  ServerError:
    description: Server Error

securityDefinitions:
  basic:
    type: basic

security:
  - basic: []


externalDocs:
  description: Apache Sling Documentation
  url: 'http://sling.apache.org/documentation.html'
